title: Quickhacks
description: Quickhacks
baseurl: "/quickhacks" # the subpath of your site, e.g. /blog
url: "https://albertattard.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude:
  [
    ".idea/",
    "bin/",
    "lib/",
    "node_modules/",
    "script/",
    "*.gemspec",
    "*.gem",
    "build.sh",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "package.json",
    "package-lock.json",
    "Rakefile",
    "README.md",
    "run.sh",
  ]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/quickhacks.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Quickhacks on GitHub":
    - "https://github.com/albertattard/quickhacks-source"

# Footer content appears at the bottom of every page's main content
footer_content: 'Copyright &copy; Albert Attard. Distributed by an <a href="https://opensource.org/licenses/Apache-2.0">Apache License 2.0.</a>'

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking
ga_tracking: G-PE3DWJG4PK
# Use GDPR compliant Google Analytics settings
ga_tracking_anonymize_ip: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
