version: "3.9"

services:
  jupyter:
    container_name: "quickhacks-docker-jupyter-jupyter"
    build: "docker/jupyter"
    ports:
      - "8888:8888"
    volumes:
      - "jupyter:/home/jovyan/work"
    healthcheck:
      start_period: "5s"
      interval: "5s"
      retries: 5
    restart: "always"
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - "quickhacks"

volumes:
  jupyter:
    name: "quickhacks-docker-jupyter-jupyter"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "./work"

networks:
  quickhacks:
    name: "quickhacks-docker-jupyter-network"
