on:
  push:
    branches:
      - main

name: Build Site

jobs:

  site:
    name: Build Jekyll site (v4.2.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the site in the jekyll/builder container
        run: |
          docker run --rm \
          --volume="${{ github.workspace }}:/srv/jekyll" \
          jekyll/builder:4.2.0 /bin/bash -c "gem install bundler && chmod -R 777 /srv/jekyll && jekyll build && bundle exec just-the-docs rake search:init"

  assets:
    name: Format and test CSS and JS
    runs-on: ubuntu-latest
    needs: [site]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm test

  publish:
    name: Publish to GitHub Pages repo
    runs-on: ubuntu-latest
    needs: [site, assets]
    steps:
      - name: Publish to GitHub Pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_site'
          destination-github-username: 'albertattard'
          destination-repository-name: 'quickhacks'
          user-email: albertattard@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
